language: node_js
node_js:
- '0.12'
- '0.10'
before_install:
- npm install -g bower
- npm install -g gulp
install:
- npm install
before_script:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: f8ngE/9XoLMlXXGPNRgzlTbZeaOL3HNdYZT3j097BXCRpU1YCMzDsTkSWLNvfBDgwsjT6fK+8G8dc8L/BrpwUjDvsdNR/l1hsWlvRcoLH3glT82R3mwtMb813sNap+TUBDL3J1sl2LxNRR0WoKxr7+GedfzDYztBZAFqj+7qB2v5zAPcrJSTq/ZD5Le0nMICnxTJmaMgOgHJxEcDtjKEyQPMCxwSago4+Hl9kLmgGMPyPaCy3k5+GHoDVFEhd7T3ikkbAyrQxcJ5Y2RAKWNzyTeO/LYENQTRrWoGVDPyWLxmoZOkmpWJdaGCcx/0TZ9b1SCEfnSQqA2Arg6zACmJhTMwGMSy9x0eDacDGR0yGQelBeAx4qCy83+d8juwFI+pWMGRC1W9ZKLBeCfyKyTds4h2WdJ2uBEfBEJQrnkULbzWwyWVGt3v8T5bvRApwGjCMKAt6Z1Z8KVIlTiDiPYTHZd+cFK6mSbrurLcXeqV7fDCPNFmN5ufXtCjpdR+5CLEDFw5wFt2cBv6urtPGU/hd2TTdUSjUISsMDSgaYWHccVIGX/klCquZEEuTovUCNqk2yRDwNdTs5GC4Pm7c5BB6xc6R6zkJPHwWbELe/Tpyu9efkpIhFoGvg5ToH77ZAEm5FT2+/HT86JdlGeFAg8TjbS9oCcjuvWl/7CvnxK2qEg=
  app: mortal-kongress
