var fixtures = {};

// a real example of a congressman object returned by govtrack api 
fixtures.congressMemberFromGovtrack = { 
  bioguideid: 'R000605',
  birthday: '1954-10-24',
  committeeassignments: 
  [ { committee: 2598,
      id: 192913,
      person: 412669,
      role: 'member',
      role_label: 'Member' },
    { committee: 2599,
      id: 192957,
      person: 412669,
      role: 'member',
      role_label: 'Member' },
    { committee: 2601,
      id: 193841,
      person: 412669,
      role: 'member',
      role_label: 'Member' },
    { committee: 2594,
      id: 194832,
      person: 412669,
      role: 'member',
      role_label: 'Member' },
    { committee: 2658,
      id: 194901,
      person: 412669,
      role: 'member',
      role_label: 'Member' },
    { committee: 2845,
      id: 195261,
      person: 412669,
      role: 'chairman',
      role_label: 'Chairman' },
    { committee: 2602,
      id: 195548,
      person: 412669,
      role: 'member',
      role_label: 'Member' },
    { committee: 2595,
      id: 195593,
      person: 412669,
      role: 'member',
      role_label: 'Member' },
    { committee: 2837,
      id: 196043,
      person: 412669,
      role: 'member',
      role_label: 'Member' },
    { committee: 2838,
      id: 196057,
      person: 412669,
      role: 'member',
      role_label: 'Member' },
    { committee: 2620,
      id: 196457,
      person: 412669,
      role: 'member',
      role_label: 'Member' },
    { committee: 2850,
      id: 196624,
      person: 412669,
      role: 'member',
      role_label: 'Member' } ],
  cspanid: null,
  firstname: 'Mike',
  gender: 'male',
  gender_label: 'Male',
  id: 412669,
  lastname: 'Rounds',
  link: 'https://www.govtrack.us/congress/members/mike_rounds/412669',
  middlename: '',
  name: 'Sen. Mike Rounds [R-SD]',
  namemod: '',
  nickname: '',
  osid: 'N00035187',
  pvsid: null,
  roles: 
  [ { caucus: null,
      congress_numbers: [Object],
      current: true,
      description: 'Junior Senator from South Dakota',
      district: null,
      enddate: '2021-01-03',
      id: 43730,
      leadership_title: null,
      party: 'Republican',
      person: 412669,
      phone: '202-224-5842',
      role_type: 'senator',
      role_type_label: 'Senator',
      senator_class: 'class2',
      senator_class_label: 'Class 2',
      senator_rank: 'junior',
      senator_rank_label: 'Junior',
      startdate: '2015-01-06',
      state: 'SD',
      title: 'Sen.',
      title_long: 'Senator',
      website: 'http://www.rounds.senate.gov' } ],
  sortname: 'Rounds, Mike (Sen.) [R-SD]',
  twitterid: 'SenatorRounds',
  youtubeid: null
};

// a real example of a congressman's vote object returned by govtrack api 
fixtures.memberVoteFromGovtrack = { created: '2015-01-20T14:50:00',
  id: 30560711,
  option: { id: 445109, key: '+', value: 'Yea', vote: 116144 },
  person: 
   { bioguideid: 'R000605',
     birthday: '1954-10-24',
     cspanid: null,
     firstname: 'Mike',
     gender: 'male',
     gender_label: 'Male',
     id: 412669,
     lastname: 'Rounds',
     link: 'https://www.govtrack.us/congress/members/mike_rounds/412669',
     middlename: '',
     name: 'Sen. Mike Rounds [R-SD]',
     namemod: '',
     nickname: '',
     osid: 'N00035187',
     pvsid: null,
     sortname: 'Rounds, Mike (Sen.) [R-SD]',
     twitterid: 'SenatorRounds',
     youtubeid: null },
  person_role: 
   { caucus: null,
     congress_numbers: [ 114, 115, 116 ],
     current: true,
     description: 'Junior Senator from South Dakota',
     district: null,
     enddate: '2021-01-03',
     id: 43730,
     leadership_title: null,
     party: 'Republican',
     person: 412669,
     phone: '202-224-5842',
     role_type: 'senator',
     role_type_label: 'Senator',
     senator_class: 'class2',
     senator_class_label: 'Class 2',
     senator_rank: 'junior',
     senator_rank_label: 'Junior',
     startdate: '2015-01-06',
     state: 'SD',
     title: 'Sen.',
     title_long: 'Senator',
     website: 'http://www.rounds.senate.gov' },
  vote: 
   { category: 'procedural',
     category_label: 'Procedural',
     chamber: 'senate',
     chamber_label: 'Senate',
     congress: 114,
     created: '2015-01-20T14:50:00',
     id: 116144,
     link: 'https://www.govtrack.us/congress/votes/114-2015/s4',
     margin: 0.151515,
     missing_data: false,
     number: 4,
     percent_plus: 0.57,
     question: 'On the Motion to Table S.Amdt. 13 to S.Amdt. 2 to S. 1 (Keystone XL Pipeline Act)',
     question_details: null,
     related_amendment: 5639,
     related_bill: 335663,
     required: '1/2',
     result: 'Motion to Table Agreed to',
     session: '2015',
     source: 'senate',
     source_label: 'senate.gov',
     total_minus: 42,
     total_other: 1,
     total_plus: 57,
     vote_type: 'On the Motion to Table S.Amdt. 13 to S.Amdt. 2 to S. 1 (Keystone XL Pipeline Act)' },
  voter_type: 'member',
  voter_type_label: 'Member of Congress',
  voteview_extra_code: '' };

module.exports = fixtures;
